apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: lgtm
spec:
  type: ClusterIP
  selector:
    app: lgtm
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: otel
  labels:
    app: otel
spec:
  type: ClusterIP
  selector:
    app: lgtm
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      containers:
        - name: lgtm
          image: grafana/otel-lgtm:latest
          ports:
            - containerPort: 3000
            - containerPort: 4317
            - containerPort: 4318
          volumeMounts:
            - name: data
              mountPath: /data/tempo
              subPath: tempo
            - name: data
              mountPath: /data/grafana
              subPath: grafana
            - name: data
              mountPath: /data/loki
              subPath: loki
            - name: data
              mountPath: /data/prometheus
              subPath: prometheus
            - name: data
              mountPath: /data/pyroscope
              subPath: pyroscope
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: mutations.gatekeeper.sh/v1
kind: ModifySet
metadata:
  name: pod-mutation-otel
spec:
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["Pod"]
    excludedNamespaces:
      - kube-*
      - cert-manager
      - crossplane-*
      - gatekeeper-*
      - platform
  location: "spec.containers[name:*].env"
  parameters:
    values:
      fromList:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel.platform:4318
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: http/protobuf