---
apiVersion: v1
kind: Service
metadata:
  name: otel
  labels:
    app: otel
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: alloy
  ports:
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
---
apiVersion: mutations.gatekeeper.sh/v1
kind: ModifySet
metadata:
  name: pod-mutation-otel
spec:
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["Pod"]
    excludedNamespaces:
      - kube-*
      - cert-manager
      - crossplane-*
      - gatekeeper-*
      - platform
  location: "spec.containers[name:*].env"
  parameters:
    values:
      fromList:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel.platform:4318
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: http/protobuf