before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

brews:
  - dependencies:
      - name: kubernetes-cli
      - name: helm
      - name: kind

    tap:
      owner: adrianliechti
      name: homebrew-tap

    commit_author:
      name: Adrian Liechti
      email: adrian@localhost

scoop:
  bucket:
    owner: adrianliechti
    name: scoop-bucket

  commit_author:
    name: Adrian Liechti
    email: adrian@localhost
