apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - image: grafana/loki:3.1.0
        name: loki
        args:
        - -config.file=/config.yaml
        volumeMounts:
        - name: config
          mountPath: /config.yaml
          subPath: config.yaml
        - name: data
          mountPath: /loki
        resources: {}
      volumes:
      - name: config
        configMap:
          name: loki
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    app: loki
spec:
  ports:
  - name: http
    protocol: TCP
    port: 3100
  selector:
    app: loki
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
data:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    common:
      instance_addr: 127.0.0.1

      replication_factor: 1
      
      path_prefix: /loki
      
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules

      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-10-24
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    ruler:
      alertmanager_url: http://alertmanager:9093
    
    analytics:
      reporting_enabled: false