apiVersion: mutations.gatekeeper.sh/v1
kind: ModifySet
metadata:
  name: pod-mutation-otel
spec:
  applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["Pod"]
    excludedNamespaces:
      - kube-*
      - cert-manager
      - crossplane-*
      - gatekeeper-*
      - platform
  location: "spec.containers[name:*].env"
  parameters:
    values:
      fromList:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel.monitoring:4318
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: http/protobuf
