---
apiVersion: v1
kind: ConfigMap
metadata:
  name: update-ca-certificates
  namespace: cert-manager
data:
  trust-ca.sh: |
    echo "$TRUSTED_CERT"
    if [ -d "/usr/local/share/ca-certificates" ]; then
      echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/ca.crt && update-ca-certificates
    elif [ -d "/etc/pki/ca-trust/source/anchors" ]; then
      echo "$TRUSTED_CERT" > /etc/pki/ca-trust/source/anchors/ca.crt && update-ca-trust
    fi
    systemctl restart containerd
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ca-trust
  namespace: cert-manager
  labels:
    app: ca-trust
spec:
  selector:
    matchLabels:
      app: ca-trust
  template:
    metadata:
      labels:
        app: ca-trust
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
        - name: update-ca-certificates
          command: ["nsenter"]
          args: ["--mount=/proc/1/ns/mnt", "--", "sh", "-c", "$(UPDATE_SCRIPT)"]
          image: debian
          env:
            - name: UPDATE_SCRIPT
              valueFrom:
                configMapKeyRef:
                  name: update-ca-certificates
                  key: trust-ca.sh
            - name: TRUSTED_CERT
              valueFrom:
                secretKeyRef:
                  name: root
                  key: ca.crt
          securityContext:
            privileged: true
      containers:
        - name: sleep
          image: k8s.gcr.io/pause:3.1
