apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: adrianliechti/loop-registry
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
          resources: {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  type: ClusterIP
  selector:
    app: registry
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry
  labels:
    app: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry-proxy
  labels:
    app: registry-proxy
spec:
  selector:
    matchLabels:
      app: registry-proxy
  template:
    metadata:
      labels:
        app: registry-proxy
    spec:
      initContainers:
        - name: hosts-patcher
          image: busybox
          securityContext:
            privileged: true
          command:
            [
              "sh",
              "-c",
              "grep -q 'registry' /mnt/hosts || echo 127.0.0.1 registry registry.loop >> /mnt/hosts",
            ]
          volumeMounts:
            - name: hosts
              mountPath: /mnt/hosts
      containers:
        - name: proxy
          image: adrianliechti/loop-proxy
          args: ["-port", "5000", "-target", "http://registry:5000"]
          ports:
            - containerPort: 5000
              hostIP: 127.0.0.1
              hostPort: 5000
          resources: {}
      volumes:
        - name: hosts
          hostPath:
            path: /etc/hosts
