apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry
  namespace: loop
spec:
  secretName: registry-tls
  dnsNames:
    - registry.loop
    - registry
    - localhost
  issuerRef:
    name: root
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: loop
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: adrianliechti/loop-registry
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
          resources: {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: loop
  labels:
    app: registry
spec:
  type: ClusterIP
  selector:
    app: registry
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry
  namespace: loop
  labels:
    app: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry-proxy
  namespace: loop
  labels:
    app: registry-proxy
spec:
  selector:
    matchLabels:
      app: registry-proxy
  template:
    metadata:
      labels:
        app: registry-proxy
    spec:
      initContainers:
        - name: hosts-patcher
          image: busybox
          command:
            [
              "sh",
              "-c",
              "grep -q 'registry' /mnt/hosts || echo 127.0.0.1 registry registry.loop >> /mnt/hosts",
            ]
          volumeMounts:
            - name: hosts
              mountPath: /mnt/hosts
      containers:
        - name: proxy
          image: adrianliechti/loop-proxy:test
          args:
            [
              "-port",
              "5000",
              "-target",
              "http://registry:5000",
              "-key-file",
              "certs/tls.key",
              "-cert-file",
              "certs/tls.crt",
            ]
          ports:
            - containerPort: 5000
              hostIP: 127.0.0.1
              hostPort: 5000
          volumeMounts:
            - name: certs
              mountPath: "/app/certs"
          resources: {}
      volumes:
        - name: certs
          secret:
            secretName: registry-tls
        - name: hosts
          hostPath:
            path: /etc/hosts
