apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: monitoring
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alertmanager
    alertmanager: monitoring
  ports:
    - name: http
      port: 9093
      protocol: TCP
      targetPort: 9093
