apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
spec:
  secretName: linkerd-identity-issuer
  duration: 24h
  renewBefore: 1h
  commonName: identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth
  issuerRef:
    name: platform
    kind: Issuer
    group: cert-manager.io
