apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-demo
  labels:
    app: ingress-demo
spec:
  selector:
    matchLabels:
      app: ingress-demo
  template:
    metadata:
      labels:
        app: ingress-demo
    spec:
      containers:
        - name: server
          image: nginxdemos/hello
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-demo
  labels:
    app: ingress-demo
spec:
  type: ClusterIP
  selector:
    app: ingress-demo
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo
spec:
  ingressClassName: nginx
  rules:
    - host: demo.example.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingress-demo
                port:
                  name: http
