apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye
spec:
  params:
  - name: username
    type: string
  steps:
    - name: goodbye
      image: public.ecr.aws/docker/library/ubuntu:latest
      script: |
        #!/bin/bash
        echo "Goodbye $(params.username)!"