apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: echo
      image: public.ecr.aws/docker/library/alpine:3
      script: |
        #!/bin/sh
        echo "Hello World" 